modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="redpocket"
version="1.0.0"
displayName="redpocket"
displayURL="https://auzer.ct.ws/"
credits="https://auzer.ct.ws/"
authors="auzer, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.redpocket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration